include ../bench/parallelDefsANN

REQUIRE = ../utils/beamSearch.h index.h  ../utils/check_nn_recall.h ../utils/NSGDist.h ../utils/parse_results.h ../utils/graph_disk.h ../utils/point_range.h
BENCH = neighbors

# Add debugging flag (-g)
CXXFLAGS += -g
CFLAGS += -g

include ../bench/MakeBench
